### ISSUE TITLE
Support python 3.6

### ISSUE THREAD

**Issue by mathben** [SiLab-Bonn/pyLandau#10]
Hi,
Do you know if pyLaudau work with python 3.6?
Only the package 3.4 is published : https://pypi.python.org/pypi/pyLandau

Thanks for you help

**Comment by DavidLP** [comment]
Sure, there is no dependency on the python version in this package. Python 3.6 is [tested](https://github.com/SiLab-Bonn/pyLandau/blob/master/.travis.yml#L7) and works. But pre-compiled binaries for Windows (that you do not have to use Cython to compile the c-code)are only provided up to Python 3.4.

**Comment by DavidLP** [comment]
If you think that binaries for Windows and Python 3.6 are useful please open a new issue.
