### ISSUE TITLE
installation via pip crashes

### ISSUE THREAD

**Issue by malindasds** [SiLab-Bonn/pylandau#13]
Hi I'm trying to install your package using pip and the installation crashes with this error:

Running setup.py install for pylandau ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8jaydccc/pylandau/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-veo_ma19/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pyLandau
    copying pyLandau/__init__.py -> build/lib.linux-x86_64-3.5/pyLandau
    running egg_info
    writing requirements to pylandau.egg-info/requires.txt
    writing dependency_links to pylandau.egg-info/dependency_links.txt
    writing top-level names to pylandau.egg-info/top_level.txt
    writing pylandau.egg-info/PKG-INFO
    reading manifest file 'pylandau.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'docs'
    writing manifest file 'pylandau.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.5/pyLandau/cpp
    copying pyLandau/cpp/pylandau.cpp -> build/lib.linux-x86_64-3.5/pyLandau/cpp
    copying pyLandau/cpp/pylandau.pyx -> build/lib.linux-x86_64-3.5/pyLandau/cpp
    copying pyLandau/cpp/pylandau_src.cpp -> build/lib.linux-x86_64-3.5/pyLandau/cpp
    running build_ext
    building 'pylandau' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/pyLandau
    creating build/temp.linux-x86_64-3.5/pyLandau/cpp
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -IpyLandau/cpp -I/home/iwsatlas1/desilva/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c pyLandau/cpp/pylandau.cpp -o build/temp.linux-x86_64-3.5/pyLandau/cpp/pylandau.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    pyLandau/cpp/pylandau.cpp:16:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by malindasds** [comment]
I'm using a linux 16.04 computer btw. I'm guessing this package is only for Windows?

**Comment by DavidLP** [comment]
No, this package is for all operating systems. Since this package contains c-code that has to be compiled you have to provide a working build environment for python: https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

I checked with Ubuntu 18 and the necessary package ```libpython-dev``` is available after I installed `pip`: ```sudo apt install python-pip```

You can try the same.

**Comment by malindasds** [comment]
Yes it worked! I followed the instructions you sent and reinstalled using pip and it worked. Thank you!
