### ISSUE TITLE
Install pylandau on homebrew python build

### ISSUE THREAD

**Issue by ChronoBro** [SiLab-Bonn/pylandau#14]
Hi, 

I tried installing this package via pip using the homebrew python3.7 build (on Mac OS Sierra) and it would not compile since it couldn't locate the numpy headers correctly. 

I then downloaded your package and tried to install it through setup.py and ran into some errors such as,

"pyLandau/cpp/pylandau.cpp:12110:22: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?"

When I changed all of the instances of tstate->exc* to tstate->curexc* in the source it seemed to build correctly as I am able to use the package.  

Thought you would like to know so that your package is compatible with Mac OS.

**Comment by DavidLP** [comment]
Thank you for letting me know. I guess this could be fixed by installing `cython` before trying to compile. Likely the cython generated c file that is shipped with this package is not working with a Mac OS compiler.

**Comment by DavidLP** [comment]
Please check #14. It has likely something to do with your development environment and is not really related to this package. I might consider uploading a binary wheel for Mac OS...
