### ISSUE TITLE
enable eta<1 (scale parameter)?

### ISSUE THREAD

**Issue by liuxiaoyuyuyu** [SiLab-Bonn/pylandau#20]
Is it possible to enable eta<1 for the Landau distribution? It will be useful for fitting the signal of a scintillator detector. When a particle goes through the detector, the deposited energy follows a Landau distribution and the width(scale) of the Landau distribution depends on the material and thickness of the detector and it can be less than one.

**Comment by ChristianBesp** [comment]
Have you tried using eta < 1 already? I do not see any limitations in the code and it is working for me with eta of at least 0.01. There is a limitation of 1e-9 for stability reasons, but I doubt you are hitting that with a scintillator signal.

**Comment by liuxiaoyuyuyu** [comment]
Hi, when I set eta<1, I got the warning:WARNING: eta < 1 not supported and set to 1! Scale x to fix. And eta was indeed set to 1.

**Comment by ChristianBesp** [comment]
I see, this was still the case in version 2.1.0 which is the latest one on pip. The current `master` (and 2.1.2rc) branch of the repo has a lot of stability fixes including allowing eta < 1. If you do not want to clone the code and install manually, there will be a new release very soon (hopefully this week) that will also be released to pip (see #19).

**Comment by liuxiaoyuyuyu** [comment]
Great! Thanks!

**Comment by jasqs** [comment]
Hi,

when could we expect the new 2.1.2 version on pip?

**Comment by cbespin** [comment]
> when could we expect the new 2.1.2 version on pip?
Thanks for getting back to the issue @jasqs. I had some trouble building the package for a pip release and then had no time to check again. I will put it on top of my list and let you know when it's done

**Comment by cbespin** [comment]
@jasqs @liuxiaoyuyuyu The new release is now live, version 2.2.0. Please note, I had to drop support for python 3.7

I will close this issue now. If there is another problem, also related to the new release, please open another issue.
