### ISSUE TITLE
Getting a Langauss fit for Alpha spectrometry data

### ISSUE THREAD

**Issue by Gomeztroika** [SiLab-Bonn/pylandau#26]
I would like to get a Langauss or Landau distribution fitting my data from Alpha spectra I have out of a PIPS detector. I am an intern in      Radioactive Measures Laboratory at the University of Basque Country and I want to get characteristics from alpha peaks out of the distribution I get from this.
![1-s2 0-S0168900211002725-gr1](https://user-images.githubusercontent.com/106329932/178439227-75ee9992-e7a0-46e3-b51a-bc6a875d5440.jpg)
My data is a text file wich plotted turns to be 3 well differences peaks:
![newplot](https://user-images.githubusercontent.com/106329932/178439875-916e81c0-085d-492a-9c84-9feed3cfae97.png)
I want the input for the **pylandau** to be each one of these peaks (inverted, since the real spectra has the "tail" to the left) wich would be an array that plotted is this:
![newplot (1)](https://user-images.githubusercontent.com/106329932/178440527-3f042c45-6c56-44f9-941c-3e89a96c9a06.png)
Is a one dimensional array in which each term has the number of counts corresponding to a channel from the detector. 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/106329932/178441565-d4cb2216-24de-4342-b370-e0fd9fc20fe0.png">
I don't know if it is possible to get those 9 peak characteristics out of the distribution built by **pylandau** code, but I would be interested in getting them to feed a Neural Network. The final idea is to get this Neural Network to identify automatically a peak and be able to distinguish overlapped peaks, but of course this has nothing to do directly with your code, is just to give some context. 
I have very little programming knowledge so would like to get some help with this.

**Comment by leloup314** [comment]
Hi @Gomeztroika, thanks for using the issue tracker and providing the detailed description. Sorry for the late reply but currently it is vacation season around here.
As you have correctly stated yourself already, your "issue" is not related to the `pylandau` package but rather generic. Unfortunately, we cannot provide help regarding application-specific user problems. I wish you the best of luck with your idea
